### ISSUE TITLE
Update "Features - Patient Records" of User Guide

### ISSUE THREAD

**Issue by didymental** [AY2122S1-CS2103-W14-1/tp#14]
Move the draft UG content into the User Guide page in your repository. Update the content as necessary. If a feature is not implemented in the current version, you can either omit it from the UG or mark it as 'Coming soon'.

**Comment by rish-16** [comment]
Hi, can I clarify the draft UG is the Google Docs right? I need to take whatever is in **Features >> Patient Records** and move it to `UserGuide.md` in my local `tp` repo?

**Comment by didymental** [comment]
Hi @rish-16, thanks for the question. Yes, please do the changes in your local ```tp``` repo, before making a pull request to the team repo. As discussed and agreed, do let Yuxin know so that he can review your pull request and merge. I'd suggest doing the changes in a branch on your personal repo (e.g. ```branch-draft-UG```), before making the pull request. Let me know if more clarification is needed! Thanks!

**Comment by rish-16** [comment]
Hey @didymental, thanks for the quick reply. Can I delete the existing content within `UserGuide.md` under `Features`? I am going to create a new subsection called `Patient Records` under `Features`.

**Comment by rish-16** [comment]
I've finished this in PR #17. Waiting to merge into `main`. Thank you, @didymental. Will close this issue once merging has taken place.
