### ISSUE TITLE
[PE-D] Expected outcome described in user guide not the same as actual application outcome

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-W14-1/tp#220]
The user guide expected outcomes for each command does not align with what is shown on the application.

For example, pt edit should give me the following response as per the user guide:
![image.png](https://raw.githubusercontent.com/markuslim24/ped/main/files/2d00199d-fd74-4253-947c-b8c6f35cf999.png)

However I get this:
![image.png](https://raw.githubusercontent.com/markuslim24/ped/main/files/6ff01600-35ba-4045-ab7b-4efe4539e563.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: markuslim24/ped#5

**Comment by gycgabriel** [comment]
Duplicate. See issue #207 instead
