### ISSUE TITLE
Medical History not showing invalid command format on ParseException

### ISSUE THREAD

**Issue by gycgabriel** [AY2122S1-CS2103-W14-1/tp#239]
**How to Reproduce:**
Enter invalid medical entry input containing `#@$%^!`
e.g. `pt add n/Jjoshen Lim p/99998888 e/joshen@gmail.com a/123 Clementi Road SG293821 m/diabetes@#$%`

**Current Result**
No medical history recorded

**Expected Result**
Invalid Command Format

![image](https://user-images.githubusercontent.com/77230723/139724247-2f56f5c3-b8c2-4028-9bf9-c681e8e76851.png)

**Comment by didymental** [comment]
@gycgabriel think this issue was resolved with an earlier PR #236 

<img width="1268" alt="Screenshot 2021-11-03 at 11 58 38 AM" src="https://user-images.githubusercontent.com/51285113/140008224-2d4188c5-d09c-4899-83c3-ef0e585ae496.png">
