### ISSUE TITLE
Implement maximum field lengths for inputs

### ISSUE THREAD

**Issue by huyuxin0429** [AY2122S1-CS2103-W14-1/tp#258]
Due to the variety of UI issues that are caused by oversize inputs, I recommend implementing reasonable field size limitations for all inputs.

**Done**:
- [x] appoinrment
- [x] medical history
- [x] prescription
- [x] patient

**Comment by gycgabriel** [comment]
What method did you use to restrict field size, can point to the part of the code that you did it? Thanks

**Comment by gycgabriel** [comment]
![image](https://user-images.githubusercontent.com/77230723/140722039-71507e38-51b8-41ea-a4e0-90aa1583470c.png)


Email, Medical History
